name: moodiesapp
description: Moodies App - Kids Mood Tracker (Firebase)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_messaging: ^16.2.0
  firebase_core: ^4.7.0

  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.0
  audioplayers: ^6.6.0
  permission_handler: ^11.1.0
  intl: ^0.19.0

  share_plus: ^12.0.2

  awesome_snackbar_content: ^0.1.6

  lottie: ^3.3.0          # animations (optional)
  google_fonts: ^6.3.2

  hive_flutter: ^1.1.0
  confetti: ^0.8.0
  flutter_local_notifications: ^19.5.0

#  ABC Games
  animate_do: ^3.0.2
  url_launcher: ^6.2.5

  flutter_swiper_view: ^1.1.8
  auto_size_text: ^3.0.0
  flutter_drawing_board: ^0.5.0
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.2.0
  floodfill_image: ^0.0.8
  flutter_launcher_icons:

  equatable: ^2.0.5

  flutter_bloc: ^9.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/abcgames/
    - assets/fonts/
    - assets/abcgames/app_icons/
    - assets/abcgames/new_gif/
    - assets/abcgames/images/new_button/
    - assets/abcgames/images/setting_button/
    - assets/abcgames/images/word_img/
    - assets/abcgames/words/
    - assets/abcgames/audio/
    - assets/abcgames/game/
    - assets/abcgames/draw_img/

  fonts:
    - family: ChocoCooky
      fonts:
        - asset: assets/fonts/chococooky.ttf
    - family: NanumPen
      fonts:
        - asset: assets/fonts/nanum_pen_script_regular.ttf
    - family: Chiki
      fonts:
        - asset: fonts/Chiki.ttf
    - family: SuezOneRegular
      fonts:
        - asset: fonts/SuezOne-Regular.ttf
    - family: GROBOLD
      fonts:
        - asset: fonts/GROBOLD.ttf
    - family: Suravaram
      fonts:
        - asset: fonts/Suravaram-Regular.ttf
